export const LOAD_USERS_ALL = 'LOAD_USERS_ALL';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const CREATE_SKILL = 'CREATE_SKILL';
export const DELETE_SKILL = 'DELETE_SKILL';
export const LOAD_SKILLS_ALL = 'LOAD_SKILLS_ALL';

export const CREATE_LOCATION  = 'CREATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const LOAD_LOCATIONS_ALL = 'LOAD_LOCATIONS_ALL';

export const CREATE_DISCIPLINE = 'CREATE_DISCIPLINE';
export const DELETE_DISCIPLINE = 'DELETE_DISCIPLINE';
export const LOAD_DISCIPLINES_ALL = 'LOAD_DISCIPLINES_ALL';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const LOAD_PROJECTS_ALL = 'LOAD_PROJECTS_ALL';
export const LOAD_PROJECTS_MOST_RECENT = 'LOAD_PROJECTS_MOST_RECENT';

export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const DELETE_FEEDBACK = 'DELETE_FEEDBACK';

export const GET_ADMIN = 'GET_ADMIN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const UPDATE_PASSWORD = 'UPDATED_PASSWORD';

export const LOAD_ORGANIZATION_ALL = 'LOAD_ORGANIZATION_ALL';
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION';