export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_MOST_RECENT_PROJECTS_SUCCESS =
  'LOAD_MOST_RECENT_PROJECTS_SUCCESS';
